---
- name: Creating additional groups 
  group: name="{{ item }}"
  with_items:
    - "{{ users_groups }}"

- name: Creating users
  user:
    name={{ item.name | mandatory }}
    comment="{{ item.comment | mandatory }}"
    groups={{ item.groups | default([]) | join(',') }}
    shell={{ item.shell | default('/bin/bash') }}
    state={{ item.state | default('present') }}
    remove={{ item.remove | default('no') }}
    password="*NP*"
  with_items:
    - "{{ users_users }}"

- name: users | Adding authorized_keys
  authorized_key:
    user={{ item.0.name }}
    key="{{ item.1.key | mandatory }}"
    state={{ item.1.state | default('present') }}
  with_subelements:
    - "{{ users_users }}"
    - ssh_keys

- name: sudo without password for users
  copy:
    content: '{{ item.name | mandatory }} ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/extra_user_{{ item.name | mandatory }}
    validate: '/usr/sbin/visudo -cf %s'
    mode: 0440
  with_items:
    - "{{ users_users }}"